source 'https://github.com/CocoaPods/Specs.git'

target 'TLFormView', :exclusive => true do
  pod "TLFormView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TLFormView", :path => "../"

  
end
